function serializeForInlineScript(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}

export function createHtmlBridgeScript(streamId: string, bridgeToken: string): string {
  const serializedStreamId = serializeForInlineScript(streamId);
  const serializedBridgeToken = serializeForInlineScript(bridgeToken);

  return [
    '<script data-dt-bridge>',
    '(() => {',
    `  const streamId = ${serializedStreamId};`,
    `  const token = ${serializedBridgeToken};`,
    '  let requestCounter = 0;',
    '  const pending = new Map();',
    '  const actionHandlers = new Map();',
    '  const REQUEST_TIMEOUT_MS = 30000;',
    '',
    '  function createError(message) {',
    '    return message instanceof Error ? message : new Error(String(message));',
    '  }',
    '',
    '  function normalizeExecArgs(programOrShell, argsOrOpts, maybeOpts) {',
    '    if (typeof programOrShell === "string" && /\\s/.test(programOrShell)',
    '        && (argsOrOpts === undefined || argsOrOpts === null',
    '            || (typeof argsOrOpts === "object" && !Array.isArray(argsOrOpts)))) {',
    '      return {',
    '        program: "sh",',
    '        args: ["-c", programOrShell],',
    '        options: (typeof argsOrOpts === "object" && argsOrOpts !== null) ? argsOrOpts : {},',
    '      };',
    '    }',
    '    return {',
    '      program: programOrShell,',
    '      args: Array.isArray(argsOrOpts) ? argsOrOpts : [],',
    '      options: (Array.isArray(argsOrOpts) ? maybeOpts : argsOrOpts) || {},',
    '    };',
    '  }',
    '',
    '  function request(kind, payload) {',
    '    return new Promise((resolve, reject) => {',
    '      const requestId = `dt-bridge-${Date.now()}-${++requestCounter}`;',
    '      const timeout = window.setTimeout(() => {',
    '        pending.delete(requestId);',
    "        reject(new Error('DeskTalk bridge request timed out.'));",
    '      }, REQUEST_TIMEOUT_MS);',
    '',
    '      pending.set(requestId, { resolve, reject, timeout });',
    '      window.parent.postMessage({',
    "        type: 'desktalk:bridge-request',",
    '        streamId,',
    '        token,',
    '        requestId,',
    '        kind,',
    '        payload,',
    "      }, '*');",
    '    });',
    '  }',
    '',
    '  function createCollectionStorage(name) {',
    '    return Object.freeze({',
    '      insert(params) {',
    "        return request('storage', { action: 'collection.insert', collection: name, params }).then(() => undefined);",
    '      },',
    '      update(id, params) {',
    "        return request('storage', { action: 'collection.update', collection: name, id, params }).then(() => undefined);",
    '      },',
    '      delete(id) {',
    "        return request('storage', { action: 'collection.delete', collection: name, id }).then(() => undefined);",
    '      },',
    '      findById(id) {',
    "        return request('storage', { action: 'collection.findById', collection: name, id }).then((result) => result.record);",
    '      },',
    '      find(filter, options) {',
    "        return request('storage', { action: 'collection.find', collection: name, filter, options }).then((result) => result.records);",
    '      },',
    '      findAll() {',
    "        return request('storage', { action: 'collection.findAll', collection: name }).then((result) => result.records);",
    '      },',
    '      count(filter) {',
    "        return request('storage', { action: 'collection.count', collection: name, filter }).then((result) => result.count);",
    '      },',
    '      compact() {',
    "        return request('storage', { action: 'collection.compact', collection: name }).then(() => undefined);",
    '      },',
    '    });',
    '  }',
    '',
    '  const actions = Object.freeze({',
    '    register(definition) {',
    '      if (!definition || typeof definition !== "object") {',
    '        throw new Error("DeskTalk.actions.register requires an action definition object.");',
    '      }',
    '      const name = typeof definition.name === "string" ? definition.name.trim() : "";',
    '      if (!name) {',
    '        throw new Error("DeskTalk.actions.register requires a non-empty action name.");',
    '      }',
    '      if (typeof definition.handler !== "function") {',
    '        throw new Error(`DeskTalk.actions.register(\"${name}\") requires a handler function.`);',
    '      }',
    '      actionHandlers.set(name, definition.handler);',
    '      return request("actions", {',
    '        action: "register",',
    '        name,',
    '        description: typeof definition.description === "string" ? definition.description : "",',
    '        params: definition.params && typeof definition.params === "object" ? definition.params : undefined,',
    '      }).then(() => undefined);',
    '    },',
    '    unregister(name) {',
    '      const normalizedName = typeof name === "string" ? name.trim() : "";',
    '      if (!normalizedName) {',
    '        throw new Error("DeskTalk.actions.unregister requires a non-empty action name.");',
    '      }',
    '      actionHandlers.delete(normalizedName);',
    '      return request("actions", { action: "unregister", name: normalizedName }).then(() => undefined);',
    '    },',
    '    clear() {',
    '      actionHandlers.clear();',
    '      return request("actions", { action: "clear" }).then(() => undefined);',
    '    },',
    '  });',
    '',
    '  const storage = Object.freeze({',
    '    get(name) {',
    "      return request('storage', { action: 'kv.get', name }).then((result) => result.value);",
    '    },',
    '    set(name, value) {',
    "      return request('storage', { action: 'kv.set', name, value }).then(() => undefined);",
    '    },',
    '    delete(name) {',
    "      return request('storage', { action: 'kv.delete', name }).then((result) => result.deleted);",
    '    },',
    '    list() {',
    "      return request('storage', { action: 'kv.list' }).then((result) => result.names);",
    '    },',
    '    collection(name) {',
    '      return createCollectionStorage(name);',
    '    },',
    '  });',
    '',
    "  window.addEventListener('message', (event) => {",
    '    const message = event.data;',
    '    if (!message || message.streamId !== streamId || message.token !== token) return;',
    "    if (message.type === 'desktalk:bridge-response') {",
    '      const pendingRequest = pending.get(message.requestId);',
    '      if (!pendingRequest) return;',
    '      pending.delete(message.requestId);',
    '      window.clearTimeout(pendingRequest.timeout);',
    '      if (message.ok) {',
    '        pendingRequest.resolve(message.result);',
    '        return;',
    '      }',
    '      pendingRequest.reject(createError(message.error || "DeskTalk bridge request failed."));',
    '      return;',
    '    }',
    "    if (message.type !== 'desktalk:invoke-action') return;",
    '    const handler = actionHandlers.get(message.actionName);',
    '    if (!handler) {',
    '      window.parent.postMessage({',
    "        type: 'desktalk:invoke-action-result',",
    '        streamId,',
    '        token,',
    '        requestId: message.requestId,',
    '        ok: false,',
    '        error: `Action \"${String(message.actionName || "")}\" is not registered.`,',
    "      }, '*');",
    '      return;',
    '    }',
    '    Promise.resolve()',
    '      .then(() => handler(message.params || {}))',
    '      .then((result) => {',
    '        window.parent.postMessage({',
    "          type: 'desktalk:invoke-action-result',",
    '          streamId,',
    '          token,',
    '          requestId: message.requestId,',
    '          ok: true,',
    '          result,',
    "        }, '*');",
    '      })',
    '      .catch((error) => {',
    '        window.parent.postMessage({',
    "          type: 'desktalk:invoke-action-result',",
    '          streamId,',
    '          token,',
    '          requestId: message.requestId,',
    '          ok: false,',
    '          error: error instanceof Error ? error.message : String(error),',
    "        }, '*');",
    '      });',
    '  });',
    '',
    '  window.DeskTalk = Object.freeze({',
    '    getState(selector) {',
    "      return request('getState', { selector });",
    '    },',
    '    request(url, options) {',
    "      return request('request', { url, options: options || {} });",
    '    },',
    '    exec(programOrShell, argsOrOpts, maybeOpts) {',
    '      const n = normalizeExecArgs(programOrShell, argsOrOpts, maybeOpts);',
    "      return request('exec', { program: n.program, args: n.args, options: n.options });",
    '    },',
    '    execute(programOrShell, argsOrOpts, maybeOpts) {',
    '      const n = normalizeExecArgs(programOrShell, argsOrOpts, maybeOpts);',
    "      return request('exec', { program: n.program, args: n.args, options: n.options });",
    '    },',
    '    actions,',
    '    storage,',
    '  });',
    '})();',
    '</script>',
  ].join('\n');
}
