import type { ToolDefinition } from '@mariozechner/pi-coding-agent';
import { Type } from '@sinclair/typebox';

const readHtmlGuidelinesSchema = Type.Object({});

const HTML_GUIDELINES = [
  '# DeskTalk HTML Guidelines',
  '',
  'Use these rules before calling `generate_html`.',
  '',
  '## Required',
  '- Use semantic `--dt-*` CSS custom properties for all colors.',
  '- Never hardcode hex, rgb, rgba, hsl, or oklch values.',
  '- Provide a complete HTML document with `<html>`, `<head>`, and `<body>`.',
  '- Inline CSS and JavaScript; do not reference external files or CDNs unless explicitly needed.',
  '',
  '## Semantic Tokens',
  '- Backgrounds: `--dt-bg`, `--dt-bg-subtle`, `--dt-surface`, `--dt-surface-hover`, `--dt-surface-active`',
  '- Text: `--dt-text`, `--dt-text-secondary`, `--dt-text-muted`, `--dt-text-on-accent`',
  '- Borders: `--dt-border`, `--dt-border-subtle`, `--dt-border-strong`',
  '- Accent: `--dt-accent`, `--dt-accent-hover`, `--dt-accent-active`, `--dt-accent-subtle`, `--dt-accent-ghost`',
  '- Status: `--dt-danger`, `--dt-danger-subtle`, `--dt-success`, `--dt-success-subtle`, `--dt-warning`, `--dt-warning-subtle`, `--dt-info`, `--dt-info-subtle`',
  '- Effects: `--dt-overlay`, `--dt-glass`, `--dt-shadow-color`',
  '',
  '## Auto-Injected Styles',
  '- A `<style data-dt-theme>` block is injected automatically at execution time.',
  "- That injected style contains the full DeskTalk `:root { --dt-* }` token set for the user's current accent color and theme mode.",
  '- It also contains a base stylesheet for `body`, headings, links, tables, cards, buttons, badges, `code`, and `pre`.',
  '- A `window.DeskTalk` bridge is also injected automatically for generated HTML previews.',
  '- `await DeskTalk.getState(selector)` supports: `desktop.summary`, `desktop.windows`, `desktop.focusedWindow`, `theme.current`, and `preview.context`.',
  '- `DeskTalk.exec` and `DeskTalk.execute` are equivalent.',
  '- Both accept a shell string: `await DeskTalk.exec("ls -la")` — this is automatically wrapped as `sh -c "ls -la"`.',
  '- Both also accept explicit arguments: `await DeskTalk.exec("ls", ["-la"])` — this runs without a shell.',
  '- An optional options object can be passed as the last argument: `await DeskTalk.exec("git", ["status"], { cwd: "subdir" })`.',
  '- Commands on the dangerous list such as `rm`, `chmod`, `sudo`, `kill`, or destructive `git` subcommands trigger a native confirmation dialog before execution.',
  '- Catastrophic commands such as filesystem formatting or `rm` against `/` are blocked outright.',
  '- Available utility classes: `.badge`, `.badge-danger`, `.badge-success`, `.badge-warning`, `.badge-info`, `.btn`, `.text-muted`, `.text-secondary`, `.accent-bg`.',
  '- **Do NOT use the `.card` CSS class or build custom card markup with `<div>`.** Always use `<dt-card>` instead (see Web Components below).',
  '- Prefer those semantic tokens and utility classes over custom color literals or one-off palette definitions.',
  '',
  '## DeskTalk Web Components',
  '- The `@desktalk/ui` component library is **automatically loaded** via a `<script>` tag injected into every generated HTML preview.',
  '- All `<dt-*>` custom elements are registered and ready to use — no additional scripts or imports needed.',
  '',
  '### `<dt-card>` (REQUIRED for card layouts)',
  '- **Always use `<dt-card>` for any card, panel, or boxed content section.** Never use `<div class="card">` or write custom card CSS.',
  '- A card container with a **solid accent-colored border** and **no border-radius**.',
  '- Attributes:',
  '  - `variant` — `"default"` (solid surface background), `"outlined"` (transparent background), `"filled"` (accent-subtle background). Default is `"default"`.',
  '- Place any content inside as children (headings, paragraphs, buttons, etc.).',
  '- Example:',
  '  ```html',
  '  <dt-card>',
  '    <h3>Status</h3>',
  '    <p>Everything is running smoothly.</p>',
  '  </dt-card>',
  '  ```',
  '- Outlined variant:',
  '  ```html',
  '  <dt-card variant="outlined">',
  '    <h3>Notice</h3>',
  '    <p>This card has a transparent background.</p>',
  '  </dt-card>',
  '  ```',
  '- **Prefer `<dt-card>` over the `.card` CSS class** for card layouts in generated HTML.',
  '',
  '### `<dt-tooltip>`',
  '- A tooltip that appears on hover/focus around its slotted child.',
  '- Attributes: `content` (text), `placement` (top|bottom|left|right), `delay` (ms), `disabled`.',
  '- Example:',
  '  ```html',
  '  <dt-tooltip content="Save file" placement="top">',
  '    <button class="btn">Save</button>',
  '  </dt-tooltip>',
  '  ```',
  '',
  '## Bridge Examples',
  '```html',
  '<script>',
  '  async function loadDesktopState() {',
  "    const desktop = await window.DeskTalk.getState('desktop.summary');",
  '    console.log(desktop.windows);',
  '  }',
  '',
  '  async function runCommand() {',
  '    // Shell-style (simple, recommended for one-liners):',
  "    const top = await window.DeskTalk.exec('top -l 1 -n 0 | head -12');",
  '    console.log(top.stdout);',
  '',
  '    // Explicit args (no shell, safer for untrusted input):',
  "    const git = await window.DeskTalk.exec('git', ['status', '--short']);",
  '    console.log(git.stdout);',
  '  }',
  '</script>',
  '```',
  '',
  '## Example',
  '```html',
  '<dt-card>',
  '  <h2>Title</h2>',
  '  <p>Description text using semantic tokens.</p>',
  '  <button class="btn">Action</button>',
  '</dt-card>',
  '```',
].join('\n');

export function createReadHtmlGuidelinesTool(): ToolDefinition {
  return {
    name: 'read_html_guidelines',
    label: 'Read HTML Guidelines',
    description:
      'Read the detailed DeskTalk HTML styling rules for generate_html, including allowed color tokens, injected classes, and examples.',
    promptSnippet: 'Read detailed styling rules before using generate_html.',
    parameters: readHtmlGuidelinesSchema,
    async execute() {
      return {
        content: [{ type: 'text', text: HTML_GUIDELINES }],
        details: { ok: true },
      };
    },
  };
}
