import type { ToolDefinition } from '@mariozechner/pi-coding-agent';
import { Type } from '@sinclair/typebox';

const readHtmlGuidelinesSchema = Type.Object({});

const HTML_GUIDELINES = [
  '# DeskTalk HTML Guidelines',
  '',
  'Use these rules before calling `generate_html`.',
  '',
  '## Required',
  '- Use semantic `--dt-*` CSS custom properties for all colors.',
  '- Never hardcode hex, rgb, rgba, hsl, or oklch values.',
  '- Provide a complete HTML document with `<html>`, `<head>`, and `<body>`.',
  '- Inline CSS and JavaScript; do not reference external files or CDNs unless explicitly needed.',
  '',
  '## Semantic Tokens',
  '- Backgrounds: `--dt-bg`, `--dt-bg-subtle`, `--dt-surface`, `--dt-surface-hover`, `--dt-surface-active`',
  '- Text: `--dt-text`, `--dt-text-secondary`, `--dt-text-muted`, `--dt-text-on-accent`',
  '- Borders: `--dt-border`, `--dt-border-subtle`, `--dt-border-strong`',
  '- Accent: `--dt-accent`, `--dt-accent-hover`, `--dt-accent-active`, `--dt-accent-subtle`, `--dt-accent-ghost`',
  '- Status: `--dt-danger`, `--dt-danger-subtle`, `--dt-success`, `--dt-success-subtle`, `--dt-warning`, `--dt-warning-subtle`, `--dt-info`, `--dt-info-subtle`',
  '- Effects: `--dt-overlay`, `--dt-glass`, `--dt-shadow-color`',
  '',
  '## Auto-Injected Styles',
  '- A `<link data-dt-theme>` stylesheet is injected automatically at execution time, loaded from the DeskTalk server.',
  "- That stylesheet contains the full DeskTalk `:root { --dt-* }` token set for the user's current accent color and theme mode.",
  '- It also contains a base stylesheet for `body`, headings, paragraphs, links, tables, cards, buttons, badges, `code`, and `pre`.',
  '- A `window.DeskTalk` bridge is also injected automatically for generated HTML previews.',
  '- `await DeskTalk.getState(selector)` supports: `desktop.summary`, `desktop.windows`, `desktop.focusedWindow`, `theme.current`, and `preview.context`.',
  '- `DeskTalk.exec` and `DeskTalk.execute` are equivalent.',
  '- Both accept a shell string: `await DeskTalk.exec("ls -la")` — this is automatically wrapped as `sh -c "ls -la"`.',
  '- Both also accept explicit arguments: `await DeskTalk.exec("ls", ["-la"])` — this runs without a shell.',
  '- An optional options object can be passed as the last argument: `await DeskTalk.exec("git", ["status"], { cwd: "subdir" })`.',
  '- Commands on the dangerous list such as `rm`, `chmod`, `sudo`, `kill`, or destructive `git` subcommands trigger a native confirmation dialog before execution.',
  '- Catastrophic commands such as filesystem formatting or `rm` against `/` are blocked outright.',
  '- Available utility classes: `.badge`, `.badge-danger`, `.badge-success`, `.badge-warning`, `.badge-info`, `.btn`, `.text-muted`, `.text-secondary`, `.accent-bg`.',
  '- **Do NOT create custom container classes** (e.g. `.card`, `.panel`, `.box`, `.section`, `.tile`, `.info-card`, `.stat-box`, or similar). Use `<dt-card>` for all visually distinct content sections (see Layout Rules below).',
  '- Prefer those semantic tokens and utility classes over custom color literals or one-off palette definitions.',
  '',
  '## Typography (Pre-Styled — Do NOT Override)',
  '- **Headings (`h1`–`h6`) and paragraphs (`p`) are fully styled by the injected base stylesheet.** Their font-size, font-weight, line-height, color, and spacing are pre-defined.',
  '- **NEVER write CSS rules, inline `style` attributes, or `<style>` blocks that target `h1`, `h2`, `h3`, `h4`, `h5`, `h6`, or `p`.** This includes font-size, font-weight, font-family, color, margin, padding, line-height, letter-spacing, and text-transform.',
  '- Simply use the native HTML tags and the injected styles will apply automatically:',
  '  - `<h1>` — 2rem, bold (700), tight letter-spacing. Use for main page titles.',
  '  - `<h2>` — 1.5rem, semibold (600). Use for section titles.',
  '  - `<h3>` — 1.25rem, semibold (600). Use for subsection titles.',
  '  - `<h4>` — 1.125rem, semibold (600). Use for card/group headings.',
  '  - `<h5>` — 1rem, semibold (600). Use for minor headings.',
  '  - `<h6>` — 0.875rem, semibold (600), uppercase. Use for label-style headings.',
  '  - `<p>` — 1rem, normal weight, secondary text color. Use for body text.',
  '- To change text color, use the utility classes `.text-muted` or `.text-secondary`, or apply `color` via `--dt-*` tokens on a wrapper — **not** on the heading/paragraph itself.',
  '',
  '## Layout Rules — Content Sections',
  '- **Every visually distinct content block MUST be wrapped in a `<dt-card>`.** This includes anything you would otherwise put in a styled `<div>` with background, border, padding, or shadow — such as cards, panels, tiles, info boxes, stat blocks, sections, containers, or groups.',
  '- **NEVER create a `<div>` (or `<section>`) with custom CSS classes for layout containers.** No `.card`, `.panel`, `.box`, `.tile`, `.info-card`, `.stat-box`, `.section-block`, `.container`, or any similar class. Use `<dt-card>` instead.',
  '- **NEVER write CSS that styles a `<div>` to look like a container** (e.g. adding background, border, border-radius, padding, or box-shadow to a class). That is what `<dt-card>` already provides.',
  '- Use plain `<div>` only for structural layout (flexbox/grid wrappers with no visual styling beyond `display`, `gap`, `flex`, `grid`, `align-items`, `justify-content`, `width`, `max-width`, and `margin`).',
  '',
  '## DeskTalk Web Components',
  '- The `@desktalk/ui` component library is **automatically loaded** via a `<script>` tag injected into every generated HTML preview.',
  '- All `<dt-*>` custom elements are registered and ready to use — no additional scripts or imports needed.',
  '',
  '### `<dt-card>`',
  '- Use for **any visually grouped content**: information panels, stat displays, status sections, feature cards, list items with backgrounds, settings groups, etc.',
  '- A card container with a **solid accent-colored border** and **no border-radius**.',
  '- Attributes:',
  '  - `variant` — `"default"` (solid surface background), `"outlined"` (transparent background), `"filled"` (accent-subtle background). Default is `"default"`.',
  '- Place any content inside as children (headings, paragraphs, buttons, etc.).',
  '- Example — stat display:',
  '  ```html',
  '  <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px;">',
  '    <dt-card>',
  '      <h6>CPU Usage</h6>',
  '      <h2>42%</h2>',
  '      <p>Normal load</p>',
  '    </dt-card>',
  '    <dt-card>',
  '      <h6>Memory</h6>',
  '      <h2>8.2 GB</h2>',
  '      <p>of 16 GB used</p>',
  '    </dt-card>',
  '    <dt-card variant="filled">',
  '      <h6>Disk</h6>',
  '      <h2>256 GB</h2>',
  '      <p>free space</p>',
  '    </dt-card>',
  '  </div>',
  '  ```',
  '- Example — simple info panel:',
  '  ```html',
  '  <dt-card variant="outlined">',
  '    <h3>Notice</h3>',
  '    <p>This card has a transparent background.</p>',
  '  </dt-card>',
  '  ```',
  '',
  '### `<dt-tooltip>`',
  '- A tooltip that appears on hover/focus around its slotted child.',
  '- Attributes: `content` (text), `placement` (top|bottom|left|right), `delay` (ms), `disabled`.',
  '- Example:',
  '  ```html',
  '  <dt-tooltip content="Save file" placement="top">',
  '    <button class="btn">Save</button>',
  '  </dt-tooltip>',
  '  ```',
  '',
  '## Bridge Examples',
  '```html',
  '<script>',
  '  async function loadDesktopState() {',
  "    const desktop = await window.DeskTalk.getState('desktop.summary');",
  '    console.log(desktop.windows);',
  '  }',
  '',
  '  async function runCommand() {',
  '    // Shell-style (simple, recommended for one-liners):',
  "    const top = await window.DeskTalk.exec('top -l 1 -n 0 | head -12');",
  '    console.log(top.stdout);',
  '',
  '    // Explicit args (no shell, safer for untrusted input):',
  "    const git = await window.DeskTalk.exec('git', ['status', '--short']);",
  '    console.log(git.stdout);',
  '  }',
  '</script>',
  '```',
  '',
  '## Example',
  '```html',
  '<h1>Dashboard</h1>',
  '<div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px;">',
  '  <dt-card>',
  '    <h3>Status</h3>',
  '    <p>All systems operational.</p>',
  '    <span class="badge badge-success">Online</span>',
  '  </dt-card>',
  '  <dt-card variant="outlined">',
  '    <h3>Activity</h3>',
  '    <p>12 events in the last hour.</p>',
  '    <button class="btn">View All</button>',
  '  </dt-card>',
  '</div>',
  '```',
].join('\n');

export function createReadHtmlGuidelinesTool(): ToolDefinition {
  return {
    name: 'read_html_guidelines',
    label: 'Read HTML Guidelines',
    description:
      'Read the detailed DeskTalk HTML styling rules for generate_html, including allowed color tokens, injected classes, and examples.',
    promptSnippet: 'Read detailed styling rules before using generate_html.',
    parameters: readHtmlGuidelinesSchema,
    async execute() {
      return {
        content: [{ type: 'text', text: HTML_GUIDELINES }],
        details: { ok: true },
      };
    },
  };
}
